### PR TITLE
[BrokenLinksH2] Fixed the broken images

### PR DESCRIPTION
**Pull request by v-sidlama**
Fixed the broken images and incorrect Markdown scripts

### CODE REVIEW

**Review by v-sidlama — COMMENTED** [review]
Corrected the image filenames

**Review by v-sidlama — COMMENTED** [review]
Corrected the images names

**Review by v-sidlama — COMMENTED** [review]
Fixed Validation warnings

**Comment by ShawnJackson** [comment]
@v-sidlama - That's a lot of image fixes in an unusually large article! I appreciate your eye for detail, but for this effort, try to refrain from making text or formatting changes that aren't related to fixing broken links and validation errors. 

"Copy information from another rate table" and "Include all employees in a rate table" are bookmarks, not images, so they shouldn't be preceded by an exclamation point. 

After you fix and verify those bookmarks, please find a reviewer who can merge this PR. I don't have write permissions in this repo.

**Review by v-sidlama — COMMENTED** [review]
Updated MD syntax error

**Comment by v-sidlama** [comment]
@theley502 please verify the fixes and merge.

**Pull request closed without merging**
