### PR TITLE
Update MicrosoftAzureandGP.md

### PR DESCRIPTION
**Pull request by Kaegun**
Fixed a few typos.

### CODE REVIEW

**Comment by SusanneWindfeldPedersen** [comment]
@Kaegun - please sign off on the CLA for us to be able to merge your PR, thanks

**Review by jswymer — APPROVED** [review]
Thanks!

**Review by jswymer — APPROVED** [review]
Looks good. Thnaks!

**Comment by Kaegun** [comment]
@microsoft-github-policy-service agree

**Comment by Kaegun** [comment]
> @Kaegun - please sign off on the CLA for us to be able to merge your PR, thanks

Done, apologies for the delay.

**Comment by Kaegun** [comment]
@SusanneWindfeldPedersen  - hi Susan, just checking whether this PR will still be merged. I think I've completed all the necessary steps and prerequisites. Apologies, it's my first time :-)

**Comment by jswymer** [comment]
@Kaegun @SusanneWindfeldPedersen Thanks!

**Pull request merged**
